AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template to create organization IAM roles and StackSet for sub-accounts."

Parameters:
  OrganizationRole:
    Type: String
    Default: CloudSiftOrgRole
    Description: "IAM Role in the Organization Management Account to assume Scanner Role."
  
  ScannerRole:
    Type: String
    Default: CloudSiftScannerRole
    Description: "IAM Role to be deployed in sub-accounts."

  BucketName:
    Type: String
    Default: "cloudsift-logs"
    Description: "S3 bucket for storing scan results."
  
  BucketRegion:
    Type: String
    Default: "us-west-2"
    Description: "AWS region where the S3 bucket should be created."

Resources:
  # 1️⃣ Organization Role (Management Account)
  OrganizationIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref OrganizationRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: "organizations.amazonaws.com"
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess

  # 2️⃣ S3 Bucket (Management Account)
  CloudSiftS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  CloudSiftS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudSiftS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::*:role/${ScannerRole}"
            Action: "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"

  # 3️⃣ StackSet for Scanner Role (Sub-Accounts)
  CloudSiftStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: "CloudSift-Scanner-Role-StackSet"
      PermissionModel: SERVICE_MANAGED
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      Capabilities:
        - CAPABILITY_NAMED_IAM
      TemplateBody: |
        AWSTemplateFormatVersion: '2010-09-09'
        Description: "Deploy Scanner IAM Role in all sub-accounts."
        Parameters:
          ScannerRole:
            Type: String
          OrganizationRoleARN:
            Type: String
        Resources:
          ScannerIAMRole:
            Type: AWS::IAM::Role
            Properties:
              RoleName: !Ref ScannerRole
              AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Principal:
                      AWS: !Ref OrganizationRoleARN
                    Action: sts:AssumeRole
              ManagedPolicyArns:
                - arn:aws:iam::aws:policy/ReadOnlyAccess
      Parameters:
        - ParameterKey: ScannerRole
          ParameterValue: !Ref ScannerRole
        - ParameterKey: OrganizationRoleARN
          ParameterValue: !Sub "arn:aws:iam::${AWS::AccountId}:role/${OrganizationRole}"

